name: audit du code

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - develop

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - name: Récupérer le code
              uses: actions/checkout@v7
            - name: Faire l'audit du répertoire
              run: |
                  echo "Audit du répertoire :"
                  ls -la
