name: audit du code

on:
    push:
        branches:
            - main
            - develop
    pull_request:
        branches:
            - develop

jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - name: Récupérer le code
              uses: actions/checkout@v7

            - name: Récupérer le chemin du cache composer
              id: composer-cache
              run: |
                  echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

            - name: Installer PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: "8.5"
                  extensions: mbstring, intl

            - name: Mise en cache
              uses: actions/cache@v6
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os}}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: |
                      ${{ runner.os}}-composer-

            - name: Installer les dépendances Composer
              run: composer install --no-progress  --prefer-dist
            - name: Lancer l'audit de sécurité
              run: composer audit --no-interaction
