# Déclarer le nom du workflow
name: audit workflow

# L'événement qui déclenche le workflow
on:
    push:
        branches:
            - main
# Les différents jobs du workflow
jobs:
    audit:
        runs-on: ubuntu-latest
        steps:
            - name: Récupérer le code
              uses: actions/checkout@v7
            - name: Faire l'audit du répertoire
              run: |
                  echo "Audit du répertoire :"
                  ls -la
