name: premier workflow

on:
    push:
        branches:
            - main
jobs:
    premier-job:
        runs-on: ubuntu-latest
        steps:
            - name: Récupérer le code
              uses: actions/checkout@v7
            - name: Lister le contenu du répertoire
              run: |
                  echo "Contenu du répertoire :"
                  ls -la
