name: Les Environnements
on: [push]


jobs:
    dev:
        runs-on: ubuntu-latest
        environment:  develop
        steps:
            - name: Déployer sur
              run: echo "Déploiement sur l'environnement develop"

    staging:
        needs: dev
        runs-on: ubuntu-latest
        environment:  staging
        steps:
            - name: Déployer sur l'environnement staging
              run: echo "Déploiement sur l'environnement staging"

    production:
        needs: staging
        runs-on: ubuntu-latest
        environment:  prod
        steps:
            - name: Déployer sur l'environnement production
              run: echo "Déploiement sur l'environnement production"

